// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Events_HelloWorld_FireOnce():Promise<void>;

export function Events_HelloWorld_Start():Promise<void>;

export function Events_HelloWorld_Stop():Promise<void>;

export function Fibonacci(arg1:number):Promise<number>;
