// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Events_HelloWorld_FireOnce() {
  return window['go']['main']['App']['Events_HelloWorld_FireOnce']();
}

export function Events_HelloWorld_Start() {
  return window['go']['main']['App']['Events_HelloWorld_Start']();
}

export function Events_HelloWorld_Stop() {
  return window['go']['main']['App']['Events_HelloWorld_Stop']();
}

export function Fibonacci(arg1) {
  return window['go']['main']['App']['Fibonacci'](arg1);
}
